- name: remove owner privillages on database
  postgresql_privs:
    db: "{{ db_creds.POSTGRESQL_DATABASE }}"
    port: "{{ db_creds.POSTGRESQL_PORT }}"
    role: "{{ bind_creds.POSTGRESQL_USER }}"
    login_host: "{{ db_creds.POSTGRESQL_HOST }}"
    login_user: "{{ db_creds.POSTGRESQL_USER }}"
    login_password: "{{ db_creds.POSTGRESQL_PASSWORD }}"
    type: database
    privs: ALL
    state: absent

- name: delte database user
  postgresql_user:
    db: "{{ db_creds.POSTGRESQL_DATABASE }}"
    name: "{{ bind_creds.POSTGRESQL_USER }}"
    password: "{{ bind_creds.POSTGRESQL_PASSWORD }}"
    port: "{{ db_creds.POSTGRESQL_PORT }}"
    login_host: "{{ db_creds.POSTGRESQL_HOST }}"
    login_user: "{{ db_creds.POSTGRESQL_USER }}"
    login_password: "{{ db_creds.POSTGRESQL_PASSWORD }}"
    encrypted: yes
    state: absent
